In [44]:
import pandas as pd
df = pd.read_excel('file/score.xlsx', index_col='지원번호')
df

       이름    학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    강나래   구로고  197   90   85  100  95  85      Python
2번    강태원   구로고  184   40   35   50  55  25        Java
3번    강호림   구로고  168   80   75   70  80  75  Javascript
4번    김수찬   구로고  187   40   60   70  75  80         NaN
5번    김재욱   구로고  188   15   20   10  35  10         NaN
6번    박동현  디지털고  202   80  100   95  85  80           C
7번    박혜정  디지털고  188   55   65   45  40  35      PYTHON
8번    승근열  디지털고  190  100   85   90  95  95          C#

In [ ]:
# 그룹화 - 통계, 평균 (그룹핑) : size, mean, sum, max, min 
# df.groupby('학교').get_group('구로고')
# df.groupby('학교').get_group('디지털고')
# df['학교'].unique() # 중복 확인 

# df.groupby('학교').size() # 학교기준으로 그룹핑을 해서 크기 

# df.groupby('학교').size()['구로고']
# df.groupby('학교').size()['디지털고']

# df.groupby('학교')['키'].mean() # 학교기준으로 키 평균 
# df.groupby('학교').mean() # 타입이 다양하기에 에러 남 
# df.groupby('학교')['국어'].mean() # 숫자 타입이면 평균 값 추출 가능 
# df.groupby('학교')[['국어','영어','수학']].mean()
# df.groupby('학교')[['국어','영어','수학']].sum()
# df.groupby('학교')[['국어','영어','수학']].min()
# df.groupby('학교')[['국어','영어','수학']].max()
df.groupby('학교')[['국어','영어','수학']].count() # size와 동일한 기능

      국어  영어  수학
학교
구로고    5   5   5
디지털고   3   3   3

In [ ]:
# 그룹핑 
df.groupby('학교').count()
df['학교'].value_counts() # df.groupby('학교').size()와 동일한 기능

학교
구로고     5
디지털고    3
Name: count, dtype: int64

In [ ]:
df['학년'] = [3,3,2,1,1,3,2,1] # 학년 추가 
df.groupby("학교")['학년'].value_counts().loc['구로고'] # row에 대한 정보:loc 
df.groupby("학교")['학년'].value_counts().loc['디지털고']
df.groupby("학교")['학년'].value_counts()

# 백분율로 표시 normalize : 원형 그래프 만들기 가능 
df.groupby("학교")['학년'].value_counts(normalize=True).loc['구로고']

학년
3    0.4
1    0.4
2    0.2
Name: proportion, dtype: float64

In [49]:
# df.groupby('학년')['키'].mean().sort_values()
# df.groupby('학년')['국어'].sum().sort_values()

df.groupby('학교')[['국어','영어']].sum().sort_values('국어') # 기준추가 
df.groupby('학교')[['국어','영어']].mean().sort_values('영어')

             국어         영어
학교
구로고   53.000000  55.000000
디지털고  78.333333  83.333333

In [ ]:
df = pd.read_csv('file/drinks.csv')
# continent 대륙별 퍼센트를 출력하시오
# df.groupby('continent').value_counts(normalize=True)
# df['continent'].value_counts(normalize=True)
df['continent'].value_counts(normalize=True)*100

# (df['continent'].value_counts(normalize=True)*100).astype(int)
# str((df['continent'].value_counts(normalize=True)*100).astype(int)+%) 
# df['continent']+%

continent
AF    31.176471
EU    26.470588
AS    25.882353
OC     9.411765
SA     7.058824
Name: proportion, dtype: float64

In [ ]:
df = pd.read_csv('file/drinks.csv')
# df.groupby('continent').size() # 그룹의 개수 확인 
df.groupby('continent').size().sort_values(ascending=False)

continent
AF    53
EU    45
AS    44
OC    16
SA    12
dtype: int64