In [33]:
import pandas as pd
df = pd.read_excel('file/score.xlsx', index_col='지원번호')

In [ ]:

df['키'].max()
df['키'].nlargest(3) # 최대값 3개 
df['키'].nsmallest(3) # 최소값 3개 

df['학교'].unique() # 중복제거 후 개수 
df['학교'].nunique() # 중복제거 후 리스트

2

In [9]:
# 기본 통계확인 - 숫자인 타입인 경우에 기본적인 통계를 보여줌. 
df.describe()

                키          국어          영어          수학         과학         사회
count    8.000000    8.000000    8.000000    8.000000   8.000000   8.000000
mean   188.000000   62.500000   65.625000   66.250000  70.000000  60.625000
std      9.985704   29.519969   26.917533   30.325614  23.754699  32.120032
min    168.000000   15.000000   20.000000   10.000000  35.000000  10.000000
25%    186.250000   40.000000   53.750000   48.750000  51.250000  32.500000
50%    188.000000   67.500000   70.000000   70.000000  77.500000  77.500000
75%    191.750000   82.500000   85.000000   91.250000  87.500000  81.250000
max    202.000000  100.000000  100.000000  100.000000  95.000000  95.000000

In [ ]:
# 컬럼의 기본정보 : 타입, null값 확인, 이름, 개수 등등 기본 정보 확인  
df.info()

<class 'pandas.DataFrame'>
Index: 8 entries, 1번 to 8번
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   이름      8 non-null      str
 1   학교      8 non-null      str
 2   키       8 non-null      int64
 3   국어      8 non-null      int64
 4   영어      8 non-null      int64
 5   수학      8 non-null      int64
 6   과학      8 non-null      int64
 7   사회      8 non-null      int64
 8   SW특기    6 non-null      str
dtypes: int64(6), str(3)
memory usage: 940.0+ bytes

       이름    학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    강나래   신림고  197   90   85  100  95  85      Python
2번    강태원   신림고  184   40   35   50  55  25        Java
3번    강호림   신림고  168   80   75   70  80  75  Javascript
4번    김수찬   신림고  187   40   60   70  75  80         NaN
5번    김재욱   신림고  188   15   20   10  35  10         NaN
6번    박동현  디지털고  202   80  100   95  85  80           C
7번    박혜정  디지털고  188   55   65   45  40  35      PYTHON
8번    승근열  디지털고  190  100   85   90  95  95          C#

In [ ]:
# 크기 확인 (8행 9열) rows=8개, cols=9개 , 괄호가 없음
df.shape

(8, 9)

In [35]:
df = pd.read_csv('file/drinks.csv')
df['continent'].unique()
# df.describe()
# df.info()
# df.shape
# df.head(10)
# df.set_index('country', inplace=True)
# df.sort_index(ascending=True)

<StringArray>
['AS', 'EU', 'AF', nan, 'SA', 'OC']
Length: 6, dtype: str

In [27]:
df = pd.read_excel('file/상장법인목록2.xlsx')
df.describe()
df.info()
df.shape
df.head(10)
df.set_index('회사명', inplace=True)
df.sort_index(ascending=True)
df

<class 'pandas.DataFrame'>
RangeIndex: 2495 entries, 0 to 2494
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   회사명     2495 non-null   str
 1   종목코드    2495 non-null   int64
 2   업종      2495 non-null   str
 3   주요제품    2477 non-null   str
 4   상장일     2495 non-null   datetime64[us]
 5   결산월     2495 non-null   str
 6   대표자명    2495 non-null   str
 7   홈페이지    2343 non-null   str
 8   지역      2495 non-null   str
dtypes: datetime64[us](1), int64(1), str(7)
memory usage: 175.6 KB

,종목코드,업종,주요제품,상장일,결산월,대표자명,홈페이지,지역
회사명,,,,,,,,
스톤브릿지벤처스,330730,기타 금융업,"창업투자, 사모투자",2022-02-25,12월,유승운,http://stonebridgeventures.vc,서울특별시
하나금융21호스팩,406760,금융 지원 서비스업,기업인수합병,2022-02-25,12월,이병찬,NaN,서울특별시
브이씨,365900,운동 및 경기용구 제조업,골프용 거리측정기,2022-02-24,12월,김준오,http://www.voicecaddie.co.kr,서울특별시
퓨런티어,370090,"측정, 시험, 항해, 제어 및 기타 정밀기기 제조업; 광학기기 제외","전장카메라모듈장비, 모바일카메라모듈장비, PC및 광원",2022-02-23,12월,배상신,http://www.furonteer.com,경기도
바이오에프디엔씨,251120,기초 의약물질 및 생물학적 제제 제조업,식물세포 유래 유효물질 및 약리물질,2022-02-21,12월,"모상현, 정대현",http://www.biofdnc.com,인천광역시
...,...,...,...,...,...,...,...,...
CJ대한통운,120,도로 화물 운송업,"Contract Logistics, 포워딩, 항만하역, 해운, 택배국제특송, SCM...",1956-07-02,12월,강신호,http://www.cjlogistics.com,서울특별시
메리츠화재,60,보험업,"손해보험(화재,해상,운송보험)",1956-07-02,12월,김용범,http://www.meritzfire.com,서울특별시
경방,50,종합 소매업,"섬유류(면사,면혼방사,면직물,면혼방직물,화섬사,화섬직물) 제조,도매,수출입",1956-03-03,12월,"김준, 김담",http://www.kyungbang.co.kr,서울특별시
유수홀딩스,700,회사 본부 및 경영 컨설팅 서비스업,지주사업,1956-03-03,12월,송영규,http://www.eusu-holdings.com,서울특별시
한진중공업홀딩스,3480,연료용 가스 제조 및 배관공급업,지주회사,1956-03-03,12월,"조남호, 조원국",http://www.hhic-holdings.com,경기도

In [ ]:
df.head # 상단에 5개만 확인
df.tail # 하단에 5개만 확인
df.head(3) # 상단 3개만 확인
df.tail(2) # 하단 2개만 확인
df.values # 배열구조로 확인 
df.index # index 확인 
df.columns # 컬럼 확인

In [ ]:
# 1차원데이터 (Series) max, min, count, mean, std 값 확인. describe 를 보여준다고 인지하면 됨
df['키'].max() # 최대값
df['키'].min()# 최소값 
df['키'].count()
df['키'].mean() # 평균값
df['키'].std()
df['이름'].count() # 이름이 몇 개인지