In [28]:
import pandas as pd
df = pd.read_excel('file/score.xlsx', index_col='지원번호')

In [ ]:

df['키'].max()
df['키'].nlargest(3) # 최대값 3개 
df['키'].nsmallest(3) # 최소값 3개 

df['학교'].unique() # 중복제거 후 개수 
df['학교'].nunique() # 중복제거 후 리스트

2

In [8]:
# 기본 통계확인 - 숫자인 타입인 경우에 기본적인 통계를 보여줌. 
df.describe()

                키          국어          영어          수학         과학         사회
count    8.000000    8.000000    8.000000    8.000000   8.000000   8.000000
mean   188.000000   62.500000   65.625000   66.250000  70.000000  60.625000
std      9.985704   29.519969   26.917533   30.325614  23.754699  32.120032
min    168.000000   15.000000   20.000000   10.000000  35.000000  10.000000
25%    186.250000   40.000000   53.750000   48.750000  51.250000  32.500000
50%    188.000000   67.500000   70.000000   70.000000  77.500000  77.500000
75%    191.750000   82.500000   85.000000   91.250000  87.500000  81.250000
max    202.000000  100.000000  100.000000  100.000000  95.000000  95.000000

In [9]:
# 컬럼의 기본정보 : 타입, null값 확인, 이름, 개수 등등 기본 정보 확인  
df.info()

<class 'pandas.DataFrame'>
Index: 8 entries, 1번 to 8번
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   이름      8 non-null      str
 1   학교      8 non-null      str
 2   키       8 non-null      int64
 3   국어      8 non-null      int64
 4   영어      8 non-null      int64
 5   수학      8 non-null      int64
 6   과학      8 non-null      int64
 7   사회      8 non-null      int64
 8   SW특기    6 non-null      str
dtypes: int64(6), str(3)
memory usage: 640.0+ bytes

In [10]:
# 크기 확인 (8행 9열) rows=8개, cols=9개 , 괄호가 없음
df.shape

(8, 9)

In [22]:
df = pd.read_csv('file/drinks.csv')
df['continent'].unique()
# df.describe()
# df.info()
# df.shape
# df.head(10)
# df.set_index('country', inplace=True)
# df.sort_index(ascending=True)

<StringArray>
['AS', 'EU', 'AF', nan, 'SA', 'OC']
Length: 6, dtype: str

In [27]:
df = pd.read_excel('file/상장법인목록2.xlsx')
df.describe()
df.info()
df.shape
df.head(10)
df.set_index('회사명', inplace=True)
df.sort_index(ascending=True)

<class 'pandas.DataFrame'>
RangeIndex: 2495 entries, 0 to 2494
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   회사명     2495 non-null   str
 1   종목코드    2495 non-null   int64
 2   업종      2495 non-null   str
 3   주요제품    2477 non-null   str
 4   상장일     2495 non-null   datetime64[us]
 5   결산월     2495 non-null   str
 6   대표자명    2495 non-null   str
 7   홈페이지    2343 non-null   str
 8   지역      2495 non-null   str
dtypes: datetime64[us](1), int64(1), str(7)
memory usage: 175.6 KB

,종목코드,업종,주요제품,상장일,결산월,대표자명,홈페이지,지역
회사명,,,,,,,,
3S,60310,전자부품 제조업,반도체 웨이퍼 캐리어,2002-04-23,03월,김세완,http://www.3sref.com,서울특별시
AJ네트웍스,95570,산업용 기계 및 장비 임대업,"렌탈(파렛트, OA장비, 건설장비)",2015-08-21,12월,박대현,http://www.ajnet.co.kr,서울특별시
AK홀딩스,6840,기타 금융업,지주사업,1999-08-11,12월,"채형석, 이석주(각자 대표이사)",http://www.aekyunggroup.co.kr,서울특별시
APS홀딩스,54620,기타 금융업,인터넷 트래픽 솔루션,2001-12-04,12월,정기로,http://www.apsholdings.co.kr,경기도
AP시스템,265520,특수 목적용 기계 제조업,디스플레이 제조 장비,2017-04-07,12월,김영주,http://www.apsystems.co.kr,경기도
...,...,...,...,...,...,...,...,...
흥국에프엔비,189980,비알코올음료 및 얼음 제조업,"과일음료(에이드베이스, 스무디, 착즙쥬스 등)",2015-08-07,12월,"박철범, 오길영",http://www.hyungkuk.com,서울특별시
흥국화재,540,보험업,손해보험,1974-12-05,12월,권중원,http://www.insurance.co.kr,서울특별시
흥아해운,3280,해상 운송업,외항화물운송업(케미컬탱커),1976-06-29,12월,이환구,http://www.heung-a.com,서울특별시
희림,37440,"건축기술, 엔지니어링 및 관련 기술 서비스업",설계 및 감리용역,2000-02-03,12월,"정영균, 이목운, 허철호 (각자대표)",http://www.heerim.com,서울특별시
힘스,238490,특수 목적용 기계 제조업,"OLED Mask 인장기, OLED Mask 검사기 등",2017-07-20,12월,김주환,http://www.hims.co.kr,인천광역시

In [ ]:
df.head # 상단에 5개만 확인
df.tail # 하단에 5개만 확인
df.head(3) # 상단 3개만 확인
df.tail(2) # 하단 2개만 확인
df.values # 배열구조로 확인 
df.index # index 확인 
df.columns # 컬럼 확인

In [ ]:
# 1차원데이터 (Series) max, min, count, mean, std 값 확인. describe 를 보여준다고 인지하면 됨
df['키'].max() # 최대값
df['키'].min()# 최소값 
df['키'].mean() # 평균값
df['키'].std() # 표준편차
df['이름'].count() # 이름이 몇 개인지

np.int64(8)